export const STORE_DATA = "STORE_DATA";
export const SELECTED_LOCATION = "SELECTED_LOCATION";
export const SELECTED_DESIGN = "SELECTED_DESIGN";
export const SELECTED_SUBDESIGN = "SELECTED_SUBDESIGN";
export const SELECTED_MODEL = "SELECTED_MODEL";
export const SELECTED_SHADE = "SELECTED_SHADE";